---

version: "3.5"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    env_file:
      - common-postgres.env
    environment:
      PGDATA: /var/lib/postgresql/data/db-files/
    volumes:
      - ./pgdata:/var/lib/postgresql/data/db-files
    networks:
      data-lake-network:

networks:
  data-lake-network: 